# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

resources:
  containers:
    - container: acrtaskcontainer  
      type: ACR
      azureSubscription: 'anshenoDev'
      resourceGroup: anumitaReg
      registry: anshenormdev
      repository: scenario1nodebaseimage
      trigger: 'true'

variables:
  system.debug: 'true'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: ACRTaskV0@0
      displayName: 'scenario1appacrtask'
      inputs:
        azureSubscription: 'anshenoDev'
        azureContainerRegistry: 'anshenormdev'
        containerRepository: 'scenario1app'
        gitHubConnection: 'github.com_Anumita'
        repositoryName: Anumita/scenario1nodeapp
        branch: master
        dockerfileOrTaskFile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
